### ISSUE TITLE
braccio_xy_bb_target.py error

### ISSUE THREAD

**Issue by Aki92-Xavier** [lots-of-things/su_chef#3]
Hi, how do i fix the error 

Traceback (most recent call last):
  File "/home/manilab/braccio_opencv_ws/src/su_chef/scripts/braccio_xy_bb_target.py", line 376, in <module>
    main()
  File "/home/manilab/braccio_opencv_ws/src/su_chef/scripts/braccio_xy_bb_target.py", line 350, in main
    bb_targetter = BraccioXYBBTargetInterface()
  File "/home/manilab/braccio_opencv_ws/src/su_chef/scripts/braccio_xy_bb_target.py", line 45, in __init__
    self.class_name_path = myargv[1]
IndexError: list index out of range

**Comment by stedn** [comment]
Hi, what was the command you used to run it? It looks like you needed to
pass an argument on the command line.

**Comment by Aki92-Xavier** [comment]
Hi, I am using jetson nano and the command that I used to run is python2.7.
How do I pass an argument on the command line.

**Comment by mohd-khalid** [comment]
I had the exact same error trying to run the script, using the same command on the README.
Any updates in this regard?

**Comment by stedn** [comment]
Could you upload or copy and paste the exact screenshot of what you ran?

**Comment by mohd-khalid** [comment]
I had `roslaunch su_chef demo.launch start_detect:=true` running in another command line window.

![Screenshot from 2023-02-14 03-42-52](https://user-images.githubusercontent.com/97974068/218608642-9ca045ed-0ad5-45cc-9e1a-7c8da96bd24f.png)

**Comment by stedn** [comment]
Could you try showing what is in that directory with an `ls`

I think you may be right that I forgot to add a command line param to the README, perhaps `models/yolo.names`.  It has been a while since I've run this and I don't have it set up right now so thanks for bearing with me as I try to debug.

**Comment by mohd-khalid** [comment]
![Screenshot from 2023-02-14 04-42-14](https://user-images.githubusercontent.com/97974068/218616514-4a9e1ac2-6617-4e30-90e6-d10078a3408e.png)

**Comment by stedn** [comment]
Can you try passing the path to yolov3.names as a command line param.  It
may be as simple as that.  If not, I will try setting it up later and let
you know.

**Comment by mohd-khalid** [comment]
I'm a beginner actually so excuse my ignorance. How to pass the path as a param, and in which command, the `roslaunch` one, or the script `rosrun` command?

**Comment by stedn** [comment]
Ah right, I mean change the command to `rosrun su_chef braccio_xy_bb_target.py <absolute path to yolov3.names>`

**Comment by mohd-khalid** [comment]
That worked but the another issue came up. The 'image' window for calibration is blank!
